title = "Data Visualisation Berlin"
invisibleSections = ["jobs"]
buildFuture = true

[markup.goldmark.renderer]
  unsafe = true

[mediaTypes]
  [mediaTypes."text/calendar"]
    suffixes = ["ics"]

[outputFormats]
  [outputFormats.JobsRSS]
    mediaType = "application/rss+xml"
    baseName = "jobs"
    isPlainText = false
    rel = "alternate"
  [outputFormats.EventsRSS]
    mediaType = "application/rss+xml"
    baseName = "events"
    isPlainText = false
    rel = "alternate"
  [outputFormats.ICal]
    mediaType = "text/calendar"
    isPlainText = true
    rel = "alternate"
  [outputFormats.ICalFeed]
    mediaType = "text/calendar"
    baseName = "events"
    isPlainText = true
    rel = "alternate"

[outputs]
  home = ["html", "rss", "jobsrss", "eventsrss", "icalfeed"]

[params]
  description = "An open list to the data visualisation scene in Berlin. All people, things and places that are related to visualisation, infographic, data art, data journalism, research, and data tools are welcome!"
  keywords = "data visualisation visualisation design infographic information graphic data-driven journalism ddj interface design"
  author = "Jonas Parnow"
  telegram = "visber"
  source = "https://github.com/Data-Visualization-Berlin/Datavis-Berlin-Website"
  imprint = "https://jonasparnow.com/imprint"
  privacy = "https://jonasparnow.com/privacy"
  direction = "ltr"

[languages]
  [languages.en]
    baseURL = "https://datavis.berlin"
    LanguageName = "English"
    languageCode = "en"
    weight = 1
    disableKinds = ["taxonomy", "section"]
  [languages.de]
    title = "Daten Visualisierung Berlin"
    baseURL = "https://de.datavis.berlin"
    description = "Eine offene List der Datenvisualisierungsszene in Berlin. Alle Menschen, Dinge und Orte, die mit Visualisierung, Infografik, Datenkunst, Datenjournalismus, Forschung und Datenanwendungen verwandt sind, sind willkommen!"
    keywords = "Visualisierung Daten Infografik Design Informationsgrafik Datenjournalismus DDJ Statistik Interfacedesign"
    LanguageName = "Deutsch"
    languageCode = "de"
    weight = 2
    disableKinds = ["taxonomy", "section"]
