[build]
command = "hugo --gc --minify"

[context.production.environment]
HUGO_VERSION = "0.117.0"
HUGO_ENV = "production"
HUGO_ENABLEGITINFO = "true"

[[headers]]
  for = "/*"
  [headers.values]
    Permissions-Policy = "interest-cohort=()"
